apiVersion: v1
kind: Service
metadata:
  name: stock-service
spec:
  type: ClusterIP
  selector:
    component: stock
  ports:
    - port: 5000
      name: http
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: stock
  template:
    metadata:
      labels:
        component: stock
    spec:
      containers:
        - name: stock
          image: stock:latest
          imagePullPolicy: Never
          resources:
            limits:
              memory: "250Mi"
              cpu: "250m"
            requests:
              memory: "250Mi"
              cpu: "250m"
          command: ["gunicorn"]
          args: ["-b", "0.0.0.0:5000", "--timeout", "600", "--worker-class", "gevent", "--workers", "1", "--worker-connections", "100", "app:app"]
          ports:
            - containerPort: 5000
          env:
            - name: ORDER_SERVICE_URL
              value: "order-service"
            - name: PAYMENT_SERVICE_URL
              value: "payment-service"
            - name: DATABASE_MANAGER_URL
              value: "connection-manager"
